[package]
name = "noise-aws-lc-rs"
version = "0.2.0"
edition = "2024"
description = "aws-lc-rs wrappers for nosie-protocol."
license = "MIT OR Apache-2.0"

[dependencies]
aws-lc-rs = "1.13"
noise-protocol = "0.2"
zeroize = "1"
